export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_USER_LOGIN_FAIL = 'AUTH_USER_LOGIN_FAIL';
export const AUTH_IS_USER_LOGGED_IN = 'AUTH_IS_USER_LOGGED_IN';

export const DB_ADD_MOVIE = 'DB_ADD_MOVIE';
export const DB_SELECT_ACTOR = 'DB_SELECT_ACTOR';
