export const AUTH_LOGIN_USER_REQUEST = 'AUTH_LOGIN_USER_REQUEST';
export const AUTH_USER_LOGIN_SUCCESS = 'AUTH_USER_LOGIN_SUCCESS';
export const AUTH_USER_LOGIN_FAIL = 'AUTH_USER_LOGIN_FAIL';
export const AUTH_IS_USER_LOGGED_IN = 'AUTH_IS_USER_LOGGED_IN';

export const DB_SELECT_ACTOR = 'DB_SELECT_ACTOR';
export const DB_READ_ACTORS_SUCCESS = 'DB_READ_ACTORS_SUCCESS';
export const DB_SAVE_TO_DB_REQUEST = 'DB_SAVE_TO_DB_REQUEST';
export const DB_SAVE_TO_DB_SUCCESS = 'DB_SAVE_TO_DB_SUCCESS';
export const DB_SAVE_TO_DB_ERROR = 'DB_SAVE_TO_DB_ERROR';
export const DB_SAVE_TO_DB_EXISTS = 'DB_SAVE_TO_DB_EXISTS';
